lifelines/lifelines

- .gitignore
- src/interp/builtin.c
- src/interp/progerr.c
- src/liflines/cscurses.c
- src/liflines/main.c
- src/liflines/miscutls.c
- src/stdlib/llabort.c
- src/stdlib/signals.c
- src/stdlib/sprintpic.c
- src/tools/btedit.c
- src/tools/dbverify.c
- src/ui/ui_cli.c
This pull request fixes format-security errors I ran into compiling on nixos.
> format-security errors

- src/gedlib/gedcom.c
Digging through my changes (I didn't use git at the time I filed this issue on sourceforge years ago), I think this is what I was trying to explain in the issue report.
> prevent overflow of keynum: fixes issue #260

- src/gedlib/charmaps.c
- src/gedlib/dblist.c
- src/gedlib/indiseq.c
- src/interp/lex.c
- src/liflines/browse.c
- src/liflines/import.c
- src/liflines/llexec.c
- src/stdlib/generic.c
- src/tools/lltest.c
This is the changes from the my previous warning clean-up brach but with all of the 'd' vs 'ld' changes reverted.  Let me know if you have any questions.
> Some clean-up and warning fixes

- README
The existing link results in a 404.
> Update project link in README

- src/interp/interp.c
- src/liflines/valgdcom.c
- src/tools/misc.c
- src/tools/toolsi.h
Fix a couple of resource leaks that sonar cloud detected.
(Note that sonarcloud doesn't seem to think that they're fixed, but that is a different battle.)
> sonarcloud cleanup

- INSTALL
- docs/dev/README.DEVELOPERS
Added instructions on how to install directly from git repo, rather than forcing people to look through the developer documentation.  Cleaned up some formatting and rewrote a few things.
Resolves #336
> Clean up INSTALL file

- AUTHORS
- ChangeLog
- INSTALL
- NEWS
- README
- build/appdata/lifelines.appdata.xml
- build/cscope.sh
- build/cscout.sh
- build/lifelines.cscout
- build/msvc6/btedit/btedit.rc
- build/msvc6/dbverify/dbVerify.rc
- build/msvc6/llexec/llexec.rc
- build/msvc6/llines/llines.rc
- build/rpm/lifelines.spec
- build/setversions.sh
- configure.ac
- docs/man/btedit.1
- docs/man/dbverify.1
- docs/man/lldump.1
- docs/man/llexec.1
- docs/man/llines.1
- src/interp/.gitignore
- src/tools/.gitignore
Version bump to 3.2.0
Updated ChangeLog, NEWS with changes
Revamp cscout support, add cscope support
Add missing files to .gitignore
> Cleanups and version bump for 3.2.0-alpha

- src/gedlib/gedcomi.h
- src/gedlib/gstrings.c
- src/gedlib/names.c
- src/gedlib/refns.c
- src/hdrs/gedcom_macros.h
- src/hdrs/llstdlib.h
- src/hdrs/standard.h
- src/interp/alloc.c
- src/interp/builtin.c
- src/interp/interp.c
- src/interp/progerr.c
- src/interp/pvalue.c
- src/liflines/askprogram.c
- src/liflines/error.c
- src/liflines/import.c
- src/liflines/menuset.c
- src/stdlib/fpattern.c
- src/stdlib/proptbls.c
- src/tools/dbverify.c
Clean up a few new warnings from gcc8.
Fix a major bug in NAME record handling.
> gcc8 warning cleanup

- src/liflines/selectdb.c
Fix various corruptions that @stevedum had reported.
> Avoid corruptions

- src/liflines/selectdb.c
> Revised dbrequested check to properly check for empty strings

- reports/least_related.ll
Version 6.0 from http://www.aegilops.com/lifelines/least_related
Permission/request provided on lines-l mailing list.
> Add Jim Eggert's least_related.ll

- reports/least_related.ll
v7 - Better first guess makes much more effective exclusion
v8 - Outputs list of IDs in path descriptions
v8.1 - Bug fixes for first persons being loners and to handle long paths
> Update least_related.ll to v8.1

- src/interp/Makefile.am
> Add comments to Makefile.am to provide hints on how to rebuild yacc.[ch]

- src/liflines/screen.c
Fixes #249
By using the global window list, which is maintained when adding windows, we no longer need to destroy each possible window individually.
> Use master window list in destroy_windows

- INSTALL
- README
As requested by @stevedum arising from #441.
> Some cleanup to INSTALL and README

- INSTALL
> Update INSTALL with additional packages required to build documentation

- src/interp/interp.c
> Add procedure arguments to symbol table

- src/liflines/llexec.c
> Various changes bring llexec and main closer together

- INSTALL
Remove some obsolete information, tidy up gettext[-devel] mentions.
> Clean up INSTALL document

- src/arch/scandir.c
Fixes #485 for Windows.
Fixes one minor issue in #484 and some style nits.
> scandir: Minor cleanup to UNIX version.  Restructure Windows version.
