src/interp/progerr.c
and a run time error occurs in the script being executed.
=> fix issue 352 llexec goes into infinite loop whn stdin is a pipe

build/setversions.sh, src/hdrs/version.h
@stevedum pointed out that the tag goes in version.h and becomes part of program banners, so move it from configure.ac to version.h.   This also better aligns with GNU standards.
=> Split version and tag handling, move tag from configure.ac to version.h

src/btree/index.c, src/gedlib/gstrings.c, src/interp/interp.c, src/liflines/miscutls.c, src/tools/misc.c
btree/index.c - files not closed.  (They will closed implicity via FATAL2 / __fatal / exit but ...)
gedlib/gstrings.c - fix a claimed buffer overrun.  (Not a bug, but rewrite code to be cleaner, sorta.)
interp/interp.c - remove break after goto (unreachable)
liflines/miscutls.c - remove self-assignment
tools/misc.c - remove self-assingment
=> Fix a few issues reported by sonarqube

src/hdrs/liflines.h, src/interp/yacc.y, src/liflines/llexec.c, src/liflines/main.c, src/liflines/selectdb.c, src/stdlib/list.c
See #379 for description is memory leaks.
Fixes:
1) Change select_database to take a STRING*, not STRING, for the dbrequested argument.  This allows any changed allocations to flow back to the caller where they can be freed up.
2) Eliminate the code that assigns an empty string to dbrequested.
src/liflines/llexec.c
src/liflines/main.c
src/liflines/selectdb.c
3) This is fixed by deleting the list node after (optionally) freeing the list element in find_delete_list_elements().
src/stdlib/list.c
4) This is fixed by calling free_iden() for each IDEN in yacc.y
src/interp/yacc.y
=> Fix memory leaks in select_database, UI window list and interp

reports/gen_index
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Also switch to UTC to be independent of timezone.
Also use ISO 8601 date format to be easier to parse.
This also avoids use of `%b` that can vary from locales.
This PR was done while working on reproducible builds for openSUSE.
=> Allow to override build date with SOURCE_DATE_EPOCH

src/gedlib/keytonod.c, src/liflines/ask.c
This is a definite but, which may have different impact on different platforms.
(This type difference apparently causes an infinite loop on MacOSX as we go through the cleanup code and repeatedly segfault.  I could not confirm on Ubuntu.)
=> Fix type of listbadkeys

src/interp/yacc.y
This avoid the double-free errors reported in #395.
=> Remove free_iden() calls that cause double frees

src/liflines/listui.c, tests/CreatingTests, tests/run_a_test, tests/string/mc_llines1.ll, tests/string/mc_llines1.llscr, tests/string/mc_llines1.out.ref
test string/mc_llines1 has double free when entering [ or ] to menu
update mc_llines1 test results
enhance run_a_test to generate a summary of valgrind errors and heap usage
when run with environment variable TESTMEMCHECK is set, also enhance valgrind
output file names to include name of program being run under valgrind.
(some tests include running 2 or 3 programs, results are now disambiguated.
=> Fix issue #413

src/btree/opnbtree.c, src/liflines/llexec.c, src/liflines/main.c, src/liflines/selectdb.c, src/tools/lldump.c
Transfer ownership of btree b_basedir to btree by saving a copy of
the basedir i.e bbasedir(btree) = strsave(dir).
This assigns clear ownership of b_basedir to creation and destruction of
a btree.  Also makes it easier for routines to manage dbused and dbrequested.
=> Remove memory leak in btree processing.

src/liflines/browse.c, src/tools/lldump.c
Fix #423 reported by Michael Hendry.
The 4 errors reported by valgrind are due to a bug in save_nkey_list().
The save_nkey_list() routine does not use the size of the list when writing to disk, but instead uses the circular buffer head/tail values (start and past_end). For an empty (uninitialized) list, start=-1 and past_end=0. This causes the routine to attempt to write the first (-1th!) entry to disk.
To resolve this I have adjusted the logic to match that of load_nkey_list(), which uses the count (size) of the list, which in this case will be 0, and will avoid the invalid array index.
I should also point out that most people will not see these errors, as history retention (SaveHistory in .linesrc) is disabled by default. The load/save_nkey_list() routines are used to load and save the …
=> Fix valgrind errors on Royal92 database open due to invalid memory accesses

build/valgrind.sh, build/valgrind.supp.ubuntu, src/gedlib/brwslist.c, src/gedlib/codesets.c, src/gedlib/gedcomi.h, src/gedlib/init.c, src/gedlib/llgettext.c, src/hdrs/gedcom.h, src/hdrs/menuitem.h, src/liflines/browse.c, src/liflines/main.c, src/liflines/menuset.c, src/liflines/screen.c
These were discovered by starting LifeLines, creating an empty database, and then exiting LifeLines.
Added a valgrind wrapper script with suppressions for ncurses memory leaks.
=> Address memory leaks on empty databases

src/liflines/screen.c
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:
screen.c:430:17: error: format not a string literal and no format arguments [-Werror=format-security]
430 |                 wprintw(win, _(qSdbrdonly));
|                 ^~~~~~~
Let's wrap all the missing places with "%s" format. It should be fine
for this case as format string don't contain any format arguments.
=> screen.c: always use "%s"-style format for printf()-style functions

.gitignore, build/.gitignore, docs/.gitignore, docs/editor/.gitignore, docs/man/.gitignore, docs/manual/.gitignore, po/.gitignore, reports/.gitignore, reports/st/.gitignore, src/.gitignore, src/arch/.gitignore, src/arch/mswin/.gitignore, src/btree/.gitignore, src/gedlib/.gitignore, src/hdrs/.gitignore, src/hdrs/mswin/.gitignore, src/interp/.gitignore, src/liflines/.gitignore, src/stdlib/.gitignore, src/tools/.gitignore, src/ui/.gitignore, tt/.gitignore
Add global rules in src/.gitignore which allows many of the .gitignore files under src/ to be removed.
Minor modifications to .gitignore which allows many of the other .gitignore files to be simplified or removed.
=> Use global rules in .gitignore

src/liflines/browse.c
Fixes #405.  Corruption is only theoretical given current key limits.  Added a comment.
=> Add comment about truncation in save_nkey_list

configure.ac, tests/Makefile.am, tests/run_a_test
=> Update configure to look for expect, and skip tests that require it when not found

src/gedlib/names.c, src/gedlib/refns.c
When freeing global pointers in NAME or REFN code, be sure to NULL out the pointers so that we don't trigger a double free.
This can happen during `reallocnamerec()`, `reallocrefnrec()` or `reallocrefnmrec()`.
Fixes #85
=> Avoid double free

src/gedlib/keytonod.c, src/gedlib/llgettext.c, src/gedlib/misc.c, src/gedlib/nodeio.c, src/gedlib/record.c, src/hdrs/gedcom.h, src/liflines/add.c, src/liflines/valgdcom.c
Fixes #439
During GEDCOM import, ensure that the key for INDIs is copied, since if there are many records that need keys resolved (eg, ASSOs), the static array used for output in rmvat() will wrap.  This will cause the INDI to get written to the wrong place.
Main change in liflines/add.c.
Cleanup and static vars for debugging in gedlib/misc.c
Code cleanup throughout.
=> Adding more than 32 ASSOs to an INDI causes corruption

src/gedlib/leaksi.h
In PR https://github.com/lifelines/lifelines/pull/459 there was a mistake which broke compilation when record debugging was disabled (which is the default).
=> Fix TRACK_RECORD_REFCNT macro

INSTALL
Fixes #438
Update INSTALL with
* minimum version of bison required
* instructions on how to install a newer bison on macOS
=> Update required version of bison, provide macOS instructions

configure.ac
Fixes #342
On FreeBSD, autoconf uses `bison -o y.tab.c`, so check for that as well as `bison -y` which is used on Linux.
=> Use alternate bison invocation on FreeBSD

src/gedlib/xlat.c, src/liflines/screen.c
Fixes #473 
When using 'Q', we basically restart the entire program internally - almost all subsystems get shut down and reinitialized.
Various global pointers in the UI subsystem were not getting NULLed properly and this caused corruption of the translation tables and xlat lists.
=> Avoid trap when using 'Q'

src/arch/scandir.c
Adapted-from: https://github.com/gpg/boa/pull/1/commits/e139b87835994d007fbd64eead6c1455d7b8cf4e
Closes: https://bugs.debian.org/1084524
=> Fix memory accounting in scandir() polyfill
